### ISSUE TITLE
A relevant paper "Transfusion: Predict the Next Token and Diffuse Images with One Multi-Modal Model"

### ISSUE THREAD

**Issue by kl2004** [lucidrains/autoregressive-diffusion-pytorch#3]
Thanks for the repo!
This is a new paper from Meta which is quite relevant: https://www.arxiv.org/abs/2408.11039

**Comment by lucidrains** [comment]
@kl2004 very cool! is it directly building off of Kaiming's team's work? i'll get around to reading it if so

**Comment by kl2004** [comment]
This paper seems to be inspired by Kaiming's paper on diffusion loss, but somehow I don't see Kaiming's paper listed in the References section.

<img width="978" alt="image" src="https://github.com/user-attachments/assets/85099808-fb45-4b3b-8c93-4addd703209f">

**Comment by lucidrains** [comment]
@kl2004 started a repo [here](https://github.com/lucidrains/transfusion-pytorch)

**Comment by lucidrains** [comment]
@kl2004 i'll also improvise a bit and add a multimodal version of the autoregressive diffusion in this repo
